### ISSUE TITLE
2.81a won't show add-on our won't install correctly

### ISSUE THREAD

**Issue by joaobrasil65** [enziop/mixamo_converter#58] opened 2020-01-05 06:35 UTC
I'm not a Blender expert but I followed your directions. I'm getting a warning saying I need Blender 2.8x our better to use the add-on, but I'm using 2.81a.

The add-on is supposedly activated but it's not showing up anywhere in the appropriate menu. Please advise if this is an issue or user error. Thanks

**Comment by joaobrasil65** [comment] 2020-01-08 16:38
![blender_mixamo addon not working](https://user-images.githubusercontent.com/11778985/71997030-414fcf80-320b-11ea-9357-1dda97d4a2ce.PNG)

blender 2.81a

just adding a screenshot

**Comment by chuklov** [comment] 2020-01-10 19:09
Have the same issue now. But looks like no one is working on this any longer.

**Comment by joaobrasil65** [comment] 2020-01-10 19:56
It works in 2.79 so I went back to it.

**Comment by chuklov** [comment] 2020-01-10 21:13
Unfortunately for me, It doesn't appear in any of the versions from 2.78 till 2.82

**Comment by enziop** [comment] 2020-03-10 12:48
duplicate of #54
now masterbranch is 2.8 version and should work again

**Closed by enziop** 2020-03-10 12:48 UTC
