### ISSUE TITLE
"hips not found"

### ISSUE THREAD

**Issue by uejoy** [enziop/mixamo_converter#35] opened 2018-06-18 14:46 UTC
hi there.
I recently used a plug-in for resource conversion and the following error "hips not found"

**Comment by enziop** [comment] 2018-06-21 23:23
what rig did you use? was it one from mixamo or a custom built rig?
if it is a custom built rig, then you have to know the name of yor hip bone and write it in the "Hip Name" field uner advanced options, as the script only looks for bones which are named hip

**Comment by enziop** [comment] 2018-07-01 15:00
I'm closing this issue, assuming that the problem was not a bug, as i havend heard any response.

**Closed by enziop** 2018-07-01 15:00 UTC

**Comment by uejoy** [comment] 2018-07-03 14:15
Thank you for your help, I have no problem in trying to operate in the office, not at home. It may be because the computer environment in the home has been adjusted, the problem has been solved, thank you very much!
