### ISSUE TITLE
2.80 Conversion Error

### ISSUE THREAD

**Issue by crossmr** [enziop/mixamo_converter#55] opened 2019-12-08 03:21 UTC
Since the plugin doesn't work in 2.81a, I fired up my 2.80 copy of blender and tried to convert an animation. 

I get the following error with the selected settings: 

![error2](https://user-images.githubusercontent.com/8927231/70383682-38be6c00-19b5-11ea-9247-3fb7efef28ad.jpg)

**Comment by enziop** [comment] 2020-03-10 15:07
sorry for the late reply, i cant reproduce the error, which rig did you use as input?
is this issue still valid?

**Comment by crossmr** [comment] 2020-03-11 00:29
Sorry, this happened 3 months ago, I can't really recall.

**Comment by enziop** [comment] 2020-09-08 13:01
this should be fixed now, kneefix should not be executed if set to (0, 0, 0)

**Closed by enziop** 2020-09-08 13:01 UTC
