### ISSUE TITLE
Wonky/Shaky

### ISSUE THREAD

**Issue by DJL3G3ND** [enziop/mixamo_converter#69] opened 2020-04-26 02:03 UTC
I dont know if this is my fault but whatever I do with the settings, it messes it up so that hes shaking left and right when he walks

**Comment by enziop** [comment] 2020-04-27 19:03
for which character and which animation does it happen? did you rig it yourself?
i can't reproduce your problem if i don't have more information

**Comment by HossamBasion** [comment] 2021-01-21 23:34
@enziop I also have the issue myself. I used the Breakdance Pack on Remy (one of the characters provided by mixamo) and used the converter on them. When I import them to Unreal 4, they look shaky like this. Here's what the breakdance 1990 animation look like: 

https://user-images.githubusercontent.com/45504896/105425226-cb43be00-5bfd-11eb-88c6-6b57ceb1774b.mp4

And here are my settings:

<img width="482" alt="Answer" src="https://user-images.githubusercontent.com/45504896/105425375-1bbb1b80-5bfe-11eb-84a8-e738c74ae1a7.png">

I noticed that this issue can be fixed by disabling the "use x", "use y" and "use z" buttons. But if I do that, enabling root motion fails to work.

**Comment by enziop** [comment] 2021-01-22 00:58
@HossamBasion Ok this looks awful. I don't yet fully understand why that happens. But if you enable Apply Rotation it seems to work fine. At least as far as i could see on my side.

**Comment by HossamBasion** [comment] 2021-01-22 02:14
Oh it didn't fix it unfortunately for me. Did you also transfer the rotation as well?

Here's my exact settings that I used now: 
<img width="156" alt="Answer" src="https://user-images.githubusercontent.com/45504896/105436643-6778bf80-5c14-11eb-88c0-26292c7fe563.png">

If it's ok with you, can I see the settings you used to fix the issue. I would like to compare.

**Comment by enziop** [comment] 2021-01-23 02:01
Im sorry for the inconviniences, try also to disable Automatic Bone Orientation.
I will make this the default soon.
![image](https://user-images.githubusercontent.com/21155833/105562433-6762e780-5d1a-11eb-89a1-5d9643d5241a.png)

**Comment by scotbayless** [comment] 2021-03-29 00:32
Hey guys, this still appears to be an issue. It doesn't happen on all animations, but it does happen pretty frequently and the offending animation are consistent. I've been using "cover to stand (2).fbx" from the Action Adventure Pack as my test file.

The problem is relatively easy to reproduce. If you import one of the problem animations (the one I mentioned above for example), you can convert it in place with Convert Single and see the glitching. At frame 31, the hip bone suddenly pops back to what appears to be the root bone's xy position (relative 0,0 perhaps?). Then, in frame 32, it pops back to its correct position and in frame 34, it pops back to 0,0 again.

Frame 30
![image](https://user-images.githubusercontent.com/6806401/112773450-00e49900-8feb-11eb-9d0e-29f750657bc6.png)
Frame 31
![image](https://user-images.githubusercontent.com/6806401/112773555-528d2380-8feb-11eb-966c-74da9fb95f1a.png)

Hope that's helpful.

**Comment by k-vladyslav** [comment] 2023-04-08 14:48
Hi @enziop, looks like I have same issue here in Blender 3.5. Did anyone find a solution or maybe a proper settings to avolid this happening?
Here is how FBX looks like in Blender 3.5 before conversion:
https://www.youtube.com/watch?v=genKFoaQ230
And here is after conversion:
https://www.youtube.com/watch?v=tC-a2zaekOc

Reproduced in Blender 3.5.
Issue could be fixed by using Blender 3.3 https://www.blender.org/download/lts/3-3/

**Comment by Juan-Ignacio-Tubio** [comment] 2023-04-09 18:47
I've been having exactly the same issue. Tried it in blender 3.5 with different configurations both on how I set up the animation on the mixamo website, how I did the conversion in the blender add-on and even on how I imported in Unreal. 

At the end of the day I downgraded to blender 3.3 through the link given by k-vladyslav and it worked perfectly. 

These were my add-on setting for the conversion : 

![Yes](https://user-images.githubusercontent.com/7827781/230791046-5280f127-52a2-4633-bde9-0c3b34d395ea.PNG)

**Comment by Blastertoad** [comment] 2023-10-17 22:22
Having same stutter issue. Using blender 3.3lts (fixes wrong root name). Tried multiple export options. Using mixamo action adventure pack cover_to_stand as test anim.

**Comment by enziop** [comment] 2024-02-14 23:48
If you can give me some example animations, with which i can reproduce the issue, is can look into this. Without some examples i will not start digging in the dark.
If you supply some complete steps to reproduce the issue including data / data links, feel free to reopen the issue.

**Closed by enziop** 2024-02-14 23:48 UTC
