### ISSUE TITLE
T pose issue

### ISSUE THREAD

**Issue by Jaastrash** [enziop/mixamo_converter#84] opened 2021-01-29 06:44 UTC
When importing the output file made from blender into Unreal (4.21.2), the Anim Sequence that appears from which the Posse Asset is made differs from the normal closed leg T pose. Did I make a mistake when converting the file or is it an Unreal Issue?

**Comment by enziop** [comment] 2021-02-18 16:07
Sorry for the late Reply, if you havent solved your Problem yet, can you give me More details?
1. Is the character Skeletal Mesh and Skeleton imported from a file that was already converted with the converter? (it should be)
2. Or are you trying to use an animation from a totally different skeleton on your character?
  - If so, there are two ways to retarget the animations to you other skeleton, either by just uploading your other character to mixamo and download the animations for your character. Or by retargeting it in Unreal using the video Guide from the readme.

**Comment by enziop** [comment] 2024-02-14 23:39
Closing due to missing information for reproducing issue.

**Closed by enziop** 2024-02-14 23:39 UTC
