### ISSUE TITLE
Not working with 2.80

### ISSUE THREAD

**Issue by ajeets1978** [enziop/mixamo_converter#59] opened 2020-01-17 23:20 UTC
I can see the plugin in Preference -> Add Ons, with a warning upgrade to 2.8x required, I am using 2.80 only ?

I don't see Mixamo anywhere in my 3D views. Please suggest.

**Comment by Gumbee** [comment] 2020-01-19 16:32
Make sure you download and install the zip for the branch blender28

**Comment by enziop** [comment] 2020-03-10 12:48
duplicate of #54
now masterbranch is 2.8 version and should work again

**Closed by enziop** 2020-03-10 12:48 UTC
