### ISSUE TITLE
Leg Rotation

### ISSUE THREAD

**Issue by DaoStriver** [enziop/mixamo_converter#28] opened 2018-04-14 20:27 UTC
Hello, Im still new to using this but im getting a weird leg rotation on Mixamo ANMI when I import them.

It seems like the right leg is always twisted inside out and the rotations throughout the Animation are messed up. but only for that leg

**Comment by enziop** [comment] 2018-04-15 09:09
can you give me some further detail on the problem?
is it a character from mixamo or a rig from the autorigger or a rig from you  which you remapped?
also does it just happen for one animation or for different animations?

**Comment by DaoStriver** [comment] 2018-04-15 13:17
So I used a Mixamo Character that I imported using the converter. I Rigged it so it would match the UE4 mannequin (I did it manually following what you said in your description). Then when I Convert then Import any animations from Mixamo both skeletons seem to have the same leg rotation issues. 

so far any animation from Mixamo has had the same issue.

If I don't use the converter on the animation I don't have the leg rotation issues... but i also don't have a root bone so they are basically worthless.

I am thinking it might be my fault using the Converter becasue it doesnt seem like anyone else is having this same issue. I'm Hoping you have some idea to what it is.

Examples:

This is the Mixamo Character
![tpose1](https://user-images.githubusercontent.com/38386353/38778802-ecf5b81c-408c-11e8-8d76-0e88e90a1031.png)

Here is the UE4 Character
![tpose2](https://user-images.githubusercontent.com/38386353/38778808-065f180c-408d-11e8-8324-6d228057aca5.png)

These are some errors
![error1](https://user-images.githubusercontent.com/38386353/38778814-1b24d678-408d-11e8-9ca9-e39ae70219f8.png)


![error2](https://user-images.githubusercontent.com/38386353/38778864-b5265e36-408d-11e8-87a4-d36f084823bd.png)



![error4](https://user-images.githubusercontent.com/38386353/38778820-24a9e7b0-408d-11e8-813c-b0d5af67b1be.png)

![error3](https://user-images.githubusercontent.com/38386353/38778847-6ca34e8a-408d-11e8-8e41-013a1e111208.png)

**Comment by enziop** [comment] 2018-05-13 15:54
At the moment i don't know what the problem ist. my best guess, is that, the roll of your bones somehow got screwed up.
You can import both, a rig from mixamo and your modified version in blender, go to
Properties->Armature->Display Pane
and enable Axes on both rigs. Then go to pose mode in both of them (reset them to restpose if they are not already by selecting all bones bith A and then pressing Alt + G (reset location) Alt + R (reset rotation) and Alt + S (reset scale)).
Compare where the z-axis of the broken leg bones are pointing in the original and in the modified version. If they are different you can go to edit mode in the modified rig, select the wrong bones and change their roll with Ctrl + R.

**Comment by enziop** [comment] 2018-06-04 10:17
could you try to convert your rig and animation where the problem appeared again with the latest version (1.1.3 or later) of the converter and report if the problem is still there, i made some updates to the processing of rotations, although your problem looks more like coming from the rig

**Comment by enziop** [comment] 2024-02-14 23:49
Closing due to no reply.

**Closed by enziop** 2024-02-14 23:49 UTC
